// Generated by https://quicktype.io

export interface ICustomersListApiResponse {
    success: boolean;
    data: ICustomerSummary[];
}

export interface ICustomerSummary {
    id: number;
    firstName: string;
    lastName: string;
    type: string;
    status: string;
    legalName: null;
    tradeName: null;
    createdAt: string;
    updatedAt: null | string;
    contactInfo: ContactInfo;
}

export interface ContactInfo {
    address: string;
    phone: string;
    email: string;
}
